# Generated by Django 4.1.13 on 2024-05-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delegasi",
            name="disetujui",
            field=models.BooleanField(default=False),
        ),
    ]
