# Generated by Django 4.1.13 on 2024-05-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_delegasi_disetujui'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegasi',
            name='alasan',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
    ]
